### ISSUE TITLE
Action Repeats

### ISSUE THREAD

**Issue by Persiflage** [frolv/kbm#1]
OS: OS X El Capitan (Version 10.11.6)
kbm: v0.1.0
Script: 
  4 -> click

When using a kbm keybind like the one above, the action will repeat at the rate specified in System Preferences -> Keyboard -> Key Repeat. Could there be a toggle to remove this behavior? With key repeat off, holding '4' would only click once. This would avoid problems with 1 input : ∞ output scripts.

**Comment by frolv** [comment]
An option to prevent hotkey repetition when a key is held down could be added
without much difficulty.

The question is what level it should be implemented at.

There are three options:
Global: a setting in the program to disable repetition altogether.
File level: add a header in a keymap file to disable repetition for all keys in
the file.
Individual key level: adding a special token to a key binding to prevent it
from being repeated.

Any preference?

**Comment by Persiflage** [comment]
I'd say File level would be most convenient and clean.

**Comment by frolv** [comment]
Ok, I'll add it to the list of planned features. Tagging as low priority for now.

**Comment by frolv** [comment]
Fully implemented as `norepeat` option on November 5 2016.
To be released in version 0.3.0.

**Comment by Persiflage** [comment]
Awesome, thanks!
