### ISSUE TITLE
Notification Flag default ON

### ISSUE THREAD

**Issue by Persiflage** [frolv/kbm#3]
Rather than forcing users to pass the '-n' flag, the notification feature should be on by default, as it's a very important and useful tool.

Obviously, toggle-able to off with the '-n' flag.

**Comment by frolv** [comment]
I initially made notifications opt-in to not bother the user with extra information.

However, after reconsideration, I agree that they are important and that most people would prefer to see them, so I've enabled them by default now and updated the `-n` flag to disable them, changing its long option equivalent to `--no-notifications`.
